version: 2.1

  orbs:
    bridgecrew: bridgecrew/bridgecrew@x.y.z

  jobs:
    build:
      executor: bridgecrew/default
      steps:
        - checkout
        - bridgecrew/scan:
            directory: '.'
            soft-fail: true
            api-key-variable: f7835a71f131ca0d5b62123895f00a0df40232f7
            prisma-api-url: https://api.prismacloud.io